### ISSUE TITLE
AccelStepper::begin

### ISSUE THREAD

**Issue by Crafter76** [sq7bti/iAccelStepper#2]
There isn't any function like this one... Can you change the main structure of the iAccelStepper, or can you write down the version of the AccelStepper lib for the current iAccelStepper?

**Comment by Crafter76** [comment]
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.cpp: In member function 'void iAccelStepper::begin(uint8_t, uint8_t, uint8_t)':
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.cpp:117:62: error: cannot call constructor 'iAccelStepper::AccelStepper' directly [-fpermissive]
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.cpp:117:62: error:   for a function-style cast, remove the redundant '::AccelStepper' [-fpermissive]
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.cpp:117:62: error: no matching function for call to 'iAccelStepper::iAccelStepper(AccelStepper::MotorInterfaceType, uint8_t&, uint8_t&)'
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.cpp:117:62: note: candidates are:
In file included from /home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.cpp:1:0:
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.h:14:3: note: iAccelStepper::iAccelStepper()
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.h:14:3: note:   candidate expects 0 arguments, 3 provided
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.h:11:7: note: iAccelStepper::iAccelStepper(const iAccelStepper&)
/home/crafter76/source_energia/libraries/iAccelStepper/iAccelStepper.h:11:7: note:   candidate expects 1 argument, 3 provided

**Comment by sq7bti** [comment]
In my attempts to make the original AccelStepper work (http://forum.stellarisiti.com/topic/574-lm4f-and-porting-of-accelstepper-lib) I had to rename the original constructor to become a begin method. Otherwise code was somehow freezing during the initialization stage. Modified (empty) constructor does nothing, the begin method called during setup() does what the original constructor was doing. For iAccelStepper to inherit, the required move of certain fields is described in README.

**Comment by sq7bti** [comment]
stale
